In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.io #Used to load the OCTAVE *.mat files
import scipy.misc #Used to show matrix as an image
import matplotlib.cm as cm #Used to display images in a specific colormap
import random #To pick random images to display
from scipy.special import expit #Vectorized sigmoid function



In [33]:
A=np.array([[1,2,3,4,5,6,7,8,9]])

B=A.reshape(3,3)
print B[1]
np.shape(B[1])

[4 5 6]


(3,)

In [11]:
B=random.sample(range(500),100)
type(B)
print B

[159, 56, 27, 198, 432, 440, 423, 30, 230, 121, 368, 47, 42, 275, 236, 175, 281, 369, 491, 126, 114, 209, 249, 384, 439, 70, 132, 492, 330, 48, 441, 185, 157, 356, 178, 471, 295, 480, 245, 166, 85, 399, 240, 385, 20, 387, 112, 127, 206, 381, 158, 448, 366, 108, 456, 445, 220, 197, 309, 395, 33, 490, 153, 382, 484, 74, 87, 239, 227, 193, 327, 416, 145, 205, 269, 345, 334, 54, 232, 62, 407, 463, 140, 67, 247, 58, 478, 221, 36, 434, 5, 133, 191, 176, 73, 125, 246, 358, 437, 171]


In [15]:
B=np.array([[1],[2],[3]])
A-B


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7],
       [-2, -1,  0,  1,  2,  3,  4,  5,  6]])

In [30]:
W=np.zeros((6,1)).reshape(-1)
print W

[ 0.  0.  0.  0.  0.  0.]


In [50]:
print B
C=np.array([[1],[2],[3]])
print np.dot(B,C)
D=[1,2,3]
print type(D)
E=B.dot(D)
print type(E)
print E
print np.shape(E)
E=B.flatten()
print np.shape(E)
F=list(E)
print F
type(F)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[14]
 [32]
 [50]]
<type 'list'>
<type 'numpy.ndarray'>
[14 32 50]
(3,)
(9,)
[1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [57]:
import random
x=random.randint(-20,10)
print x

-5
