In [3]:
import numpy as np
a=3
b=2
c=np.sum(a-b)
print c

1


In [24]:
A=np.array([[1],[1],[1]])
B=np.array([[1],[2],[3]])
C=np.hstack([A,B])
print C
print C[1,0]

[[1 1]
 [1 2]
 [1 3]]
1


In [17]:
xvals = np.linspace(-1,1.5,50)
np.shape(xvals)

(50,)

In [19]:
xval2 = np.arange(1,100,2)
np.shape(xval2)
print xval2[0], xval2[49]

1 99


In [31]:
x = np.arange(-5, 5, 1)
y = np.arange(3, 8, 1)
print x,y

xx, yy = np.meshgrid(x, y)

type(xx)
print xx
print yy

[-5 -4 -3 -2 -1  0  1  2  3  4] [3 4 5 6 7]
[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]
[[3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]]
